name: main CI/CD

on:
  push:
    branches:
      - main # Adjust to your target branch
  workflow_dispatch: # Allows manual triggering from GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: webAdminBranch # Adjust to the branch you want to use (develop or webAdminBranch)

      # List files to verify directory structure
      - name: List files
        run: ls -la 

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests (optional)
      - name: Run tests
        run: npm test
