name: main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all branches and history

      # Debug Git and verify branches
      - name: Debug Git
        run: |
          echo "Available remote branches:"
          git branch -r
          echo "Fetching branches from origin..."
          git fetch origin
          echo "Checking out webAdminBranch..."
          if git ls-remote --heads origin webAdminBranch; then
            git checkout webAdminBranch
          else
            echo "Error: webAdminBranch does not exist. Exiting."
            exit 1
          fi

      # List files
      - name: List files
        run: ls -la
